The errors were erroring out because error was undefined
> divvun-actions@1.0.0 build
> tsc

setup/index.ts:109:20 - error TS18046: 'error' is of type 'unknown'.

109     core.setFailed(error.message);
                       ~~~~~

speller/deploy/index.ts:146:24 - error TS18046: 'error' is of type 'unknown'.

146         core.setFailed(error.message);
                           ~~~~~

Found 2 errors in 2 files.

Errors  Files
     1  setup/index.ts:109
     1  speller/deploy/index.ts:146
npm notice